### PR TITLE
Remove an array as a class constant

### PR DESCRIPTION
**Pull request by iangcarroll**

### CODE REVIEW

**Comment by OwlyCode** [comment]
Hello !

Array as constant is possible since php 5.6 (which is the minimum requirement to use this library). Why do you want to change this ?

**Comment by iangcarroll** [comment]
This doesn't work on HHVM, unfortunately. I haven't tested on HHVM with PHP 7 features enabled, but I and likely others can't enable it because of issues with third party libraries.

**Comment by rustygoldcoin** [comment]
I agree with @OwlyCode Don't need to make this change. Runs on PHP7 fine.

**Comment by OwlyCode** [comment]
@iangcarroll Which version of HHVM are you using ?

**Comment by iangcarroll** [comment]
`3.12-lts`

**Comment by OwlyCode** [comment]
Ok it looks like it is not supported by HHVM at the moment : https://github.com/facebook/hhvm/issues/4277

I'll test your branch tomorrow on HHVM. If it's the only thing to fix for HHVM support I'll gladly merge.

**Comment by OwlyCode** [comment]
I checked on hhvm today. Your fix makes it work, but I also had to patch the stub twitter streaming API to pass the automated tests.

I'll merge this now, fix the tests and add travis so we get sure it does not break again on this platform.

Thank you for your time and patience !

**Pull request merged**
